stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

build:
  stage: build
  image: docker:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/mlflow:$CI_COMMIT_SHA ./mlflow
    - docker push $CI_REGISTRY_IMAGE/mlflow:$CI_COMMIT_SHA
  only:
    - main

deploy:
  stage: deploy
  image: docker/compose:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker-compose pull
    - docker-compose up -d
  environment:
    name: production
  only:
    - main